### ISSUE TITLE
Baserow installation error

### ISSUE THREAD

**Issue by jwezel** [christianhuth/helm-charts#1104]
When attempting to install baserow I got:

Error: Command failed: helm install christianhuth/baserow --version 2.1.1 --values /tmp/603509e4-ff1d-46ca-85e8-a89d604d60ca-values.yaml --namespace baserow --kubeconfig /tmp/kubeconfig-459e1c5cf283d3c30c402981ce1f23a2 --generate-name
Error: INSTALLATION FAILED: YAML parse error on baserow/templates/asgi/asgi-hpa.yaml: error converting YAML to JSON: yaml: line 21: mapping values are not allowed in this context

Kubernetes version: v1.30.1

**Comment by christianhuth** [comment]
Hi @jwezel 
Can you provide the version of the Helm Chart and the used values.yaml please.

**Comment by jwezel** [comment]
Embarrassingly I only have an edited version of the full values.yaml, so everything that's not changed is in it as well. But these are the values I used:

```
frontend.ingress.enabled=true
frontend.ingress.annotations.cert-manager.io/cluster-issuer=letsencrypt-xxxx-xxxxx-xxx
frontend.ingress.hostname=xxxxxxx.xxxxx.xxx
frontend.ingress.tls={secretName=baserow-tls, hosts=[xxxxxxx.xxxxx.xxx]}
frontend.autoscaling.enabled=true
frontend.autoscaling.maxReplicas=3
backend.asgi.autoscaling.enabled=true
backend.asgi.autoscaling.maxReplicas=3
backend.celery.autoscaling.enabled=true
backend.celery.autoscaling.maxReplicas=3
backend.wsgi.autoscaling.enabled=true
backend.wsgi.autoscaling.maxReplicas=3
postgresql.enabled=false
externalPostgresql.auth.password=xxxxxxxxxxxxxxxxxxxx
externalPostgresql.hostname=db.baserow
redis.enabled=false
externalRedis.auth.password=xxxxxxxxxxxxxxxxxxx
```

**Comment by christianhuth** [comment]
Fixed with the latest version: https://github.com/christianhuth/helm-charts/pull/1125
